#!/bin/bash

export TUPI_HOME="/usr/local/tupi"
export TUPI_SHARE="${TUPI_HOME}/share"
export TUPI_LIB="${TUPI_HOME}/lib"
export TUPI_PLUGIN="${TUPI_LIB}/plugins"
export TUPI_INCLUDE="${TUPI_HOME}/include"
export TUPI_BIN="${TUPI_HOME}/bin"

export LD_LIBRARY_PATH="${TUPI_LIB}:${TUPI_PLUGIN}:$LD_LIBRARY_PATH"

exec ${TUPI_BIN}/tupi.bin $*
